---

version: '3.2'

# Local environment should mount plaintext files as secrets
secrets:
  EZPROXY_SECRET:
    file: ./secrets/EZPROXY_SECRET
  EZPROXY_WSKEY:
    file: ./secrets/EZPROXY_WSKEY

services:
  dns:
    build:
      context: docker
      dockerfile: dnsmasq.Dockerfile
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
      - type: bind
        source: ./docker/conf/local.dns.conf
        target: /etc/dnsmasq.d/00-local.conf
    networks:
      dns:
        ipv4_address: "172.0.0.10"
  socks:
    build:
      context: docker
      dockerfile: socks.Dockerfile
    volumes:
      - type: bind
        source: ./docker/conf/sshd_config
        target: /etc/ssh/sshd_config
    ports:
      - "2022:2022"
    networks:
      - dns
    dns:
      - 172.0.0.10
    depends_on:
      - dns
  ezproxy:
    build:
      context: docker
      dockerfile: ezproxy.Dockerfile
    command: /usr/local/ezproxy/ezproxy
    volumes:
      - type: bind
        source: .
        target: /usr/local/ezproxy
    ports:
      - "2048:2048"
      - "2443:2443"
    secrets:
      - EZPROXY_SECRET
      - EZPROXY_WSKEY
    networks:
      dns:
        ipv4_address: "172.0.0.11"
    dns:
      - 172.0.0.10
    depends_on:
      - socks
networks:
  dns:
    ipam:
      config:
        - subnet: 172.0.0.0/24
